#!/usr/bin/env python3
"""Generate src/font5x7.h from the glyph art below.

The renderer writes into a raw pre-swapped RGB565 framebuffer, so it cannot use
M5GFX's text drawing without paying a byte-swap on every frame. It carries its
own 5x7 font instead. Keeping the glyphs as ASCII art here (rather than as hand-
written hex) is the whole point of this script: the art is reviewable, and the
packing is done once by a machine that does not make bit-order mistakes.

    ./tools/make-font.py            # rewrite src/font5x7.h
    ./tools/make-font.py --show     # unpack the result and print it back

Encoding: 5 bytes per glyph, one per column, bit N = row N counting from the top.
"""

import argparse
import sys
from pathlib import Path

GLYPHS = {
# Arrows live below space, in the C0 range the ASCII table leaves free. The
# Cardputer prints arrows on its ; . , / keys, so the on-screen hints have to
# be able to draw them or they cannot name the controls the player is looking at.
"\x18": "..#.. .###. #.#.# ..#.. ..#.. ..#.. ..#..",   # up
"\x19": "..#.. ..#.. ..#.. ..#.. #.#.# .###. ..#..",   # down
"\x1a": "..... ..#.. ...#. ##### ...#. ..#.. .....",   # right
"\x1b": "..... ..#.. .#... ##### .#... ..#.. .....",   # left
"0": ".###. #...# #..## #.#.# ##..# #...# .###.",
"1": "..#.. .##.. ..#.. ..#.. ..#.. ..#.. .###.",
"2": ".###. #...# ....# ...#. ..#.. .#... #####",
"3": "##### ...#. ..#.. ...#. ....# #...# .###.",
"4": "...#. ..##. .#.#. #..#. ##### ...#. ...#.",
"5": "##### #.... ####. ....# ....# #...# .###.",
"6": "..##. .#... #.... ####. #...# #...# .###.",
"7": "##### ....# ...#. ..#.. .#... .#... .#...",
"8": ".###. #...# #...# .###. #...# #...# .###.",
"9": ".###. #...# #...# .#### ....# ...#. .##..",
"A": ".###. #...# #...# ##### #...# #...# #...#",
"B": "####. #...# #...# ####. #...# #...# ####.",
"C": ".###. #...# #.... #.... #.... #...# .###.",
"D": "###.. #..#. #...# #...# #...# #..#. ###..",
"E": "##### #.... #.... ####. #.... #.... #####",
"F": "##### #.... #.... ####. #.... #.... #....",
"G": ".###. #...# #.... #.### #...# #...# .###.",
"H": "#...# #...# #...# ##### #...# #...# #...#",
"I": ".###. ..#.. ..#.. ..#.. ..#.. ..#.. .###.",
"J": "..### ...#. ...#. ...#. ...#. #..#. .##..",
"K": "#...# #..#. #.#.. ##... #.#.. #..#. #...#",
"L": "#.... #.... #.... #.... #.... #.... #####",
"M": "#...# ##.## #.#.# #.#.# #...# #...# #...#",
"N": "#...# ##..# #.#.# #..## #...# #...# #...#",
"O": ".###. #...# #...# #...# #...# #...# .###.",
"P": "####. #...# #...# ####. #.... #.... #....",
"Q": ".###. #...# #...# #...# #.#.# #..#. .##.#",
"R": "####. #...# #...# ####. #.#.. #..#. #...#",
"S": ".###. #...# #.... .###. ....# #...# .###.",
"T": "##### ..#.. ..#.. ..#.. ..#.. ..#.. ..#..",
"U": "#...# #...# #...# #...# #...# #...# .###.",
"V": "#...# #...# #...# #...# #...# .#.#. ..#..",
"W": "#...# #...# #...# #.#.# #.#.# ##.## #...#",
"X": "#...# #...# .#.#. ..#.. .#.#. #...# #...#",
"Y": "#...# #...# .#.#. ..#.. ..#.. ..#.. ..#..",
"Z": "##### ....# ...#. ..#.. .#... #.... #####",
" ": "..... ..... ..... ..... ..... ..... .....",
".": "..... ..... ..... ..... ..... .##.. .##..",
":": "..... .##.. .##.. ..... .##.. .##.. .....",
"+": "..... ..#.. ..#.. ##### ..#.. ..#.. .....",
"-": "..... ..... ..... ##### ..... ..... .....",
"/": "....# ....# ...#. ..#.. .#... #.... #....",
"!": "..#.. ..#.. ..#.. ..#.. ..#.. ..... ..#..",
"%": "#...# #...# ...#. ..#.. .#... #...# #...#",
}

FIRST, LAST = 0x18, 0x5A          # arrows .. 'Z', one contiguous run
W, H = 5, 7


def pack(art):
    rows = art.split()
    if len(rows) != H or any(len(r) != W for r in rows):
        raise ValueError(f"glyph must be {W}x{H}, got {[len(r) for r in rows]}")
    cols = []
    for x in range(W):
        bits = 0
        for y in range(H):
            if rows[y][x] == "#":
                bits |= 1 << y
        cols.append(bits)
    return cols


def unpack(cols):
    return [
        "".join("#" if cols[x] & (1 << y) else "." for x in range(W))
        for y in range(H)
    ]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--show", action="store_true", help="print the unpacked table")
    args = ap.parse_args()

    table = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        art = GLYPHS.get(ch)
        table.append((ch, pack(art) if art else [0] * W))

    if args.show:
        for ch, cols in table:
            if not any(cols):
                continue
            print(f"'{ch}'")
            for line in unpack(cols):
                print("  " + line)
        return 0

    out = [
        "// =============================================================================",
        "//  font5x7.h — the HUD font, generated by tools/make-font.py",
        "//",
        "//  GENERATED FILE — edit the glyph art in the script, not this table.",
        "//",
        "//  render.cpp writes into a pre-swapped RGB565 buffer that M5GFX's text",
        "//  drawing cannot target without a per-pixel conversion, so the HUD carries",
        "//  its own font. Uppercase plus four arrows: 0x18..0x5A, five bytes per glyph,",
        "//  one byte per column, bit N = row N from the top.",
        "// =============================================================================",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"constexpr int  FONT_W     = {W};",
        f"constexpr int  FONT_H     = {H};",
        f"constexpr char FONT_FIRST = 0x{FIRST:02X};",
        f"constexpr char FONT_LAST  = 0x{LAST:02X};",
        "",
        f"static const uint8_t kFont5x7[{LAST - FIRST + 1}][{W}] = {{",
    ]
    for ch, cols in table:
        body = ", ".join(f"0x{c:02X}" for c in cols)
        label = {" ": "space", "\x18": "up", "\x19": "down",
                 "\x1a": "right", "\x1b": "left"}.get(ch, ch)
        out.append(f"  {{ {body} }},   // {label}")
    out += ["};", ""]

    dest = Path(__file__).resolve().parent.parent / "src" / "font5x7.h"
    dest.write_text("\n".join(out))
    print(f"wrote {dest} ({LAST - FIRST + 1} glyphs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
