#!/usr/bin/env python3
"""Generate src/sprites.h from the pixel art below.

The renderer owns a raw pre-swapped RGB565 framebuffer and cannot use M5GFX's
drawing calls on it, so sprites are blitted by hand from an indexed bitmap.
Keeping the art as ASCII here — rather than as hand-written hex, or as stacks of
coloured rectangles in render.cpp — is the whole point of this script: the art
is reviewable in a diff, and the packing is done once by a machine that does not
make bit-order mistakes. tools/make-font.py does the same for the HUD font.

    ./tools/make-sprites.py            # rewrite src/sprites.h
    ./tools/make-sprites.py --show     # unpack the result and print it back

Encoding: one byte per pixel, palette index, row-major. Index 0 is transparent.
Each sprite family carries its own palette of up to 15 colours; the renderer
pre-shades that palette once per drawn instance for distance and light, so the
inner loop is a plain index-and-store.

House style for the art itself:
  '.'  transparent
  '#'  outline — always the darkest colour, always a full ring around the
       silhouette. This is what makes a sprite read against terrain of a
       similar colour, and it is drawn into the art rather than inflated at
       runtime so it costs nothing and never doubles on interior edges.
  others  shades, dark to light, so every surface has at least three.
"""

import argparse
import sys
from pathlib import Path

# Palettes. Index 0 is transparent and never appears in the art.
PALETTES = {
    "zombie": [
        ("#", (16, 18, 22)),     # outline
        ("x", (24, 30, 26)),     # eye socket
        ("a", (58, 96, 60)),     # skin, shadow
        ("b", (92, 148, 88)),    # skin, mid
        ("c", (128, 186, 118)),  # skin, lit
        ("d", (28, 60, 82)),     # trousers, shadow
        ("e", (44, 88, 116)),    # trousers, lit
        ("f", (26, 88, 76)),     # shirt, shadow
        ("g", (42, 128, 104)),   # shirt, mid
        ("h", (66, 162, 132)),   # shirt, lit
    ],
    "creeper": [
        ("#", (12, 20, 12)),
        ("x", (16, 34, 16)),     # the face
        ("a", (38, 96, 40)),     # shadow
        ("b", (66, 150, 62)),    # mid
        ("c", (98, 190, 88)),    # lit
        ("d", (128, 214, 108)),  # highlight
    ],
    "skeleton": [
        ("#", (18, 18, 22)),
        ("x", (22, 22, 28)),     # sockets
        ("a", (132, 132, 126)),  # bone, shadow
        ("b", (186, 186, 178)),  # bone, mid
        ("c", (228, 228, 220)),  # bone, lit
        ("d", (74, 52, 32)),     # bow, shadow
        ("e", (116, 84, 50)),    # bow, lit
    ],
    # The 32x32 tool pack, exactly: all four tiers index identically.
    "pick": [
        ("#", ( 32,  24,  10)),   # '#'
        ("a", ( 40,  30,  11)),   # 'a'
        ("b", ( 55,  41,  16)),   # 'b'
        ("c", ( 73,  54,  21)),   # 'c'
        ("d", (104,  78,  30)),   # 'd'
        ("e", (107,  81,  31)),   # 'e'
        ("f", (117,  88,  33)),   # 'f'
        ("g", (134, 101,  38)),   # 'g'
        ("h", (137, 103,  39)),   # 'h'
        ("i", (137, 103,  39)),   # 'i'  (padding)
    ],
    # The pack's sword. Its blade gains shades with the tier, so the diamond
    # grid is canonical and the lower tiers take the majority colour of each
    # slot -- one slot merges on wood and iron, two on stone.
    "sword": [
        ("#", ( 40,  30,  11)),   # '#'
        ("a", ( 32,  24,  10)),   # 'a'
        ("b", ( 55,  41,  16)),   # 'b'
        ("c", ( 73,  54,  21)),   # 'c'
        ("d", ( 71,  54,  20)),   # 'd'
        ("e", ( 71,  54,  20)),   # 'e'
        ("f", (137, 103,  39)),   # 'f'
        ("g", ( 71,  54,  20)),   # 'g'
        ("h", ( 89,  67,  25)),   # 'h'
        ("i", ( 89,  67,  25)),   # 'i'
    ],
    "hand": [
        ("#", ( 79,  52,  32)),    # outline -- the source's brown, not black
        ("a", ( 79,  52,  32)),    # (unused)
        ("b", ( 79,  52,  32)),    # (unused)
        ("c", (236, 192, 154)),    # skin, shaded
        ("d", (251, 207, 169)),    # skin
        ("e", (236, 192, 154)),    # (unused)
        ("f", (251, 207, 169)),    # (unused)
        ("g", (251, 207, 169)),    # (unused)
        ("h", (251, 207, 169)),    # (unused)
        ("i", (251, 207, 169)),    # (unused)
    ],
}

# ---- mobs: 16 wide, 24 tall -------------------------------------------------
#
# Two walk frames each, and for anything that swings at you, attack poses after
# them. WALK_FRAMES below says where the walk cycle stops, because the renderer
# picks a walk frame with a modulo and would otherwise deal an attack pose out
# as part of the stride.
#
# The difference between frames is deliberately large — legs swapped and the
# whole body dropped a pixel — because at ten cells a subtle cycle is invisible
# and at two cells a subtle cycle looks like a rendering fault. The same goes
# double for the swing: at sixteen pixels wide there is no room for a subtle
# gesture, so the arms come in to the body to wind up and are thrown out past
# the silhouette to strike.

ZOMBIE = ["""
....########....
...#bbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#bcccccccb#...
..#bbcaaacbb#...
...##########...
....#ffffff#....
..###gggggg###..
.#abc#gghg#cba#.
.#abc#ghhg#cba#.
.#abc#ghhg#cba#.
.#abc#gggg#cba#.
.#abc#ffff#cba#.
.#bc##ffff##cb#.
..###dddddd###..
....#dd##dd#....
....#de##ed#....
....#de##ed#....
....#de##ed#....
....#dd##dd#....
....###.###.....
................
""", """
................
....########....
...#bbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#bcccccccb#...
..#bbcaaacbb#...
...##########...
....#ffffff#....
..###gggggg###..
.#abc#gghg#cba#.
.#abc#ghhg#cba#.
.#abc#ghhg#cba#.
.#abc#gggg#cba#.
.#bc##ffff##cb#.
..###dddddd###..
....#dd##dd#....
....#ed##de#....
....#ed##de#....
....#ed##de#....
....#dd##dd#....
....##.####.....
................
""", """
....########....
...#bbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#bcccccccb#...
..#bbcaaacbb#...
...##########...
....#ffffff#....
..###gggggg###..
..#ab#gghg#ba#..
..#bc#ghhg#cb#..
..#cc#ghhg#cc#..
..####gggg####..
.....#ffff#.....
....##ffff##....
..###dddddd###..
....#dd##dd#....
....#de##ed#....
....#de##ed#....
....#de##ed#....
....#dd##dd#....
....###.###.....
................
""", """
....########....
...#bbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#bcccccccb#...
..#bbcaaacbb#...
...##########...
....#ffffff#....
#####gggggg#####
#abcc#gghg#ccba#
#bccc#ghhg#cccb#
#cccc#ghhg#cccc#
######gggg######
.....#ffff#.....
....##ffff##....
..###dddddd###..
....#dd##dd#....
....#de##ed#....
....#de##ed#....
....#de##ed#....
....#dd##dd#....
....###.###.....
................
"""]

CREEPER = ["""
................
..###########...
..#bbbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#cccxxxccc#...
..#ccxxxxxcc#...
..#ccxxxxxcc#...
..#cccxxxccc#...
..#bcccccccb#...
..###########...
...#bbbbbbb#....
...#bcccccb#....
...#bcccccb#....
...#bcdddcb#....
...#bcccccb#....
...#bbbbbbb#....
...####.####....
...#aa#.#aa#....
...#ab#.#ba#....
...#ab#.#ba#....
...####.####....
................
""", """
................
..###########...
..#bbbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#cccxxxccc#...
..#ccxxxxxcc#...
..#ccxxxxxcc#...
..#cccxxxccc#...
..#bcccccccb#...
..###########...
...#bbbbbbb#....
...#bcccccb#....
...#bcdddcb#....
...#bcccccb#....
...#bcccccb#....
...#bbbbbbb#....
..#####.####....
..#aa#..#aa#....
..#ba#..#ab#....
..#ba#..#ab#....
..####..####....
................
"""]

SKELETON = ["""
....######......
...#bbbbbb#.....
..#bcccccb#.....
..#cxxcxxc#.....
..#cxxcxxc#.....
..#ccccccc#.....
..#cacacac#.....
...########.....
.....##.........
..##bbbbbb##....
.#d#cc##cc#b#...
.#e#cc##cc#b#...
.#e#cccccc#b#...
.#e#cc##cc#b#...
.#d#cccccc#b#...
..##bbbbbb##....
....#aaaa#......
....#a##a#......
....#c##c#......
....#c##c#......
....#b##b#......
....#a##a#......
....##.##.......
................
""", """
................
....######......
...#bbbbbb#.....
..#bcccccb#.....
..#cxxcxxc#.....
..#cxxcxxc#.....
..#ccccccc#.....
..#cacacac#.....
...########.....
.....##.........
..##bbbbbb##....
.#e#cc##cc#b#...
.#e#cc##cc#b#...
.#d#cccccc#b#...
.#e#cc##cc#b#...
.#e#cccccc#b#...
..##bbbbbb##....
....#aaaa#......
....#a##a#......
....#c##c#......
....#c##c#......
....#b##b#......
...##.##........
................
"""]

# The tier palettes. The art is one grid per kind and the tier is a whole
# palette swap, not a swap of four indices inside one -- which is what the old
# hand-written kMetal table in render.cpp was, and it is gone.
TIER_PALETTES = {
    "pick": [
        # wooden
        [( 32,  24,  10), ( 40,  30,  11), ( 55,  41,  16), ( 73,  54,  21), (104,  78,  30), (107,  81,  31), (117,  88,  33), (134, 101,  38), (137, 103,  39), (137, 103,  39)],
        # stone
        [( 24,  24,  24), ( 40,  30,  11), ( 73,  73,  73), ( 73,  54,  21), (104,  78,  30), (127, 127, 127), (137, 137, 137), (154, 154, 154), (137, 103,  39), (137, 103,  39)],
        # iron
        [( 24,  24,  24), ( 40,  30,  11), ( 68,  68,  68), ( 73,  54,  21), (104,  78,  30), (193, 193, 193), (216, 216, 216), (255, 255, 255), (137, 103,  39), (137, 103,  39)],
        # diamond
        [( 23,  23,  45), ( 40,  30,  11), ( 14,  63,  54), ( 73,  54,  21), (104,  78,  30), ( 39, 178, 154), ( 43, 199, 172), ( 51, 235, 203), (137, 103,  39), (137, 103,  39)],
    ],
    "sword": [
        # wooden
        [( 40,  30,  11), ( 32,  24,  10), ( 55,  41,  16), ( 73,  54,  21), ( 71,  54,  20), ( 71,  54,  20), (137, 103,  39), ( 71,  54,  20), ( 89,  67,  25), ( 89,  67,  25)],
        # stone
        [( 40,  30,  11), ( 33,  33,  33), ( 73,  73,  73), ( 73,  54,  21), ( 90,  90,  90), ( 90,  90,  90), (137, 103,  39), ( 90,  90,  90), (120, 119, 119), (120, 119, 119)],
        # iron
        [( 40,  30,  11), ( 24,  24,  24), ( 68,  68,  68), ( 73,  54,  21), (150, 150, 150), (150, 150, 150), (137, 103,  39), (190, 190, 190), (216, 216, 216), (255, 255, 255)],
        # diamond
        [( 40,  30,  11), (  9,  45,  47), ( 14,  63,  54), ( 73,  54,  21), ( 21,  99,  85), ( 30, 138, 119), (137, 103,  39), ( 43, 199, 172), ( 51, 235, 203), (164, 253, 240)],
    ],
}

# ---- the held items: 16 x 16 ------------------------------------------------
#
# Three 16x16 cells, mirrored and recoloured into the tier palettes.
#
# These three are the reference sheet's own pixels, mirrored and recoloured.
# Nothing is redrawn. An earlier pass laid the pickaxe out from geometry and a
# later one doubled the cells to 32x32 with scale2x; both drifted off the
# source -- the shading stopped following the form and started following the
# curve -- and both were thrown away. Recolouring is the whole job here.
#
# Mirrored because the sheet holds tips up-RIGHT with handles off the
# bottom-LEFT, and render.cpp anchors held items head-top-left with the handle
# leaving by the bottom-right corner, which is where the hand is.
#
# 16x16, not 32x32, so render.cpp's SCALE is 4 rather than 2: same 64 pixels on
# the panel either way. It also means ui.cpp's hotbar icon stops decimating
# every other texel and blits the art as it is.
#
# The pickaxe's two head arms differ -- a blunt chisel up-right and a long taper
# to a point down-left -- which is the difference between a pickaxe and a
# mallet, and it comes from the sheet rather than from this file's own earlier
# and repeated failures to draw it.

# The pickaxe and the sword: 32 x 32, from a vanilla-style tool pack, one grid
# per kind with the tier carried entirely by the palette.
#
# NOT mirrored. The pack draws both tools head up-RIGHT with the handle running
# down-LEFT, and that is the way they are held: the handle crosses the palm and
# the head stands up out of the fist. An earlier pass mirrored them, from back
# when there was no hand and the handle had to leave by the bottom-right corner
# of the panel instead of entering something.
#
# The slots are ordered darkest-first, so "#" is the outline the way the rest of
# this file's art reads. The order is taken from one tier and used for all four,
# because a single grid indexes them all.
#
# The pickaxe is exact: its four tiers index identically, pixel for pixel. The
# sword is not, quite. Its blade gains shades as the tier rises -- seven colours
# on wood against ten on diamond -- so the diamond grid is canonical and the
# lower tiers take the majority colour of each slot. That merges one slot on
# wood and iron and two on stone, which is the price of one grid instead of
# four, and it is invisible at 64 panel pixels.
PICK = ["""
................................
................................
................................
................................
................................
................................
................................
................................
.........bbbb...................
........bggggbbb................
.........bbbggfgbb#.ca..........
............bbbffgg#da..........
...............bbegg#...........
.................begg#..........
................ad#eg#..........
...............cha.#e#..........
..............cha..#ee#.........
.............cda....#f#.........
............cda.....#f#.........
...........cha......#f#.........
..........cha.......#ff#........
.........cda.........#f#........
........cda..........#g#........
.......cha...........#g#........
......cha.............#.........
.....cha........................
....cda.........................
...cda..........................
..cda...........................
..aa............................
................................
................................
"""]

SWORD = ["""
................................
................................
................................
................................
................................
................................
................................
.....................bbbb.......
....................biiia.......
...................biigia.......
..................biigiia.......
.................biigiia........
................biigiia.........
...............biighia..........
..............biighha...........
.............bhighha............
............bhhghha.............
...........bhhghha..............
..........bhhghha...............
....bb...bhhghha................
....bdb.bhhehha.................
.....beahhehha..................
.....beahehha...................
......bdahha....................
......cadaa.....................
.....cf#abba....................
....cf#..aaba...................
..bbf#.....aa...................
.bdda...........................
.bdda...........................
..aa............................
................................
"""]

# The empty hand: 10 x 21, and the only one of the three that is not the weapon
# sheet's.
#
# It is a pixel-for-pixel transcription of a supplied 16x28 sprite -- every
# texel sampled and snapped to the four colours actually in that file, then
# cropped to its content. Eleven hand-drawn attempts came before it and every
# one was a mitten or a potato; reading the source's own texels took one pass.
#
# Mirrored, so the thumb is on the side of the hand the player holds a pickaxe
# with. The source's bottom edge -- it is a complete icon, closed off with an
# outline -- is dropped: the wrist has to run off the panel, not stop on it.
#
# And the wrist is EXTENDED, its last row repeated to 27 rows in all. The source
# is 21 texels tall and ends in a closed outline, because it was drawn as an
# icon; held, the swing lifts the whole hand and then turns it about the grip,
# which throws the far end of the forearm sideways as well as up, and at the
# source length that end came back onto the panel and the arm read as severed.
#
# 27 is the shortest that clears all sixteen swing frames at both amplitudes.
# Nothing of the fist is invented -- only the last row of wrist repeats -- and
# 15 pixels of arm show below the palm at rest.
#
# It draws at the tools' SCALE. Two sprites on one panel with different texel
# sizes read as a mistake, so the hand is a smaller SPRITE rather than the same
# sprite in smaller pixels: 10x21 against their 16x16, which is why render.cpp's
# blit takes the art's dimensions instead of assuming the pickaxe's.
HAND = ["""
.#######..
#c#c#c#c#.
#d#d#d#d#.
#d#d#d#d#.
#c#c#c###.
######ddd#
#ccccc##d#
#dddddcdd#
#dddddddd#
#cdddcdd#.
.#cddcc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
.#cdddc#..
"""]

SPRITES = {
    "zombie": ZOMBIE,
    "creeper": CREEPER,
    "skeleton": SKELETON,
    "pick": PICK,
    "sword": SWORD,
    "hand": HAND,
}

MOB_ORDER = ["zombie", "creeper", "skeleton"]

# How many of a family's frames are the walk cycle. Anything past this is an
# attack pose, reached from the mob's windup rather than from its stride.
WALK_FRAMES = {"zombie": 2, "creeper": 2, "skeleton": 2}

def parse(art, legend, name, idx):
    rows = [r for r in art.strip("\n").split("\n")]
    w = max(len(r) for r in rows)
    rows = [r.ljust(w, ".") for r in rows]
    out = []
    for y, row in enumerate(rows):
        line = []
        for x, ch in enumerate(row):
            if ch == ".":
                line.append(0)
            elif ch in legend:
                line.append(legend[ch])
            else:
                sys.exit(f"{name}[{idx}] row {y} col {x}: unknown glyph {ch!r}")
        out.append(line)
    return out, w, len(rows)

def emit(path):
    parts = []
    parts.append(
        "// =============================================================================\n"
        "//  sprites.h — GENERATED by tools/make-sprites.py. Do not edit by hand.\n"
        "//\n"
        "//  Indexed pixel art: one byte per pixel, palette index, row-major, 0 =\n"
        "//  transparent. Each family carries its own palette; render.cpp pre-shades it\n"
        "//  once per drawn instance for distance, light and hit flash, so the blit\n"
        "//  itself is an index and a store.\n"
        "//\n"
        "//  The outline is part of the art rather than an inflate-and-fill pass at\n"
        "//  runtime. That costs nothing, never doubles on interior edges, and is what\n"
        "//  lets a mob read against terrain of its own colour.\n"
        "// =============================================================================\n"
        "#pragma once\n\n#include <stdint.h>\n\nnamespace sprites {\n"
    )

    # Order is the emit order, and it is fixed here rather than taken from
    # SPRITES so that adding a family is a deliberate edit in two places.
    for fam in ["zombie", "creeper", "skeleton", "pick", "sword", "hand"]:
        pal = PALETTES[fam]
        legend = {ch: i + 1 for i, (ch, _) in enumerate(pal)}
        frames = SPRITES[fam]
        grids, w, h = [], None, None
        for i, art in enumerate(frames):
            g, gw, gh = parse(art, legend, fam, i)
            if w is None:
                w, h = gw, gh
            elif (gw, gh) != (w, h):
                sys.exit(f"{fam}: frame {i} is {gw}x{gh}, frame 0 is {w}x{h}")
            grids.append(g)

        up = fam.upper()
        parts.append(f"// ---- {fam} ----\n")
        parts.append(f"constexpr int {up}_W = {w};\n")
        parts.append(f"constexpr int {up}_H = {h};\n")
        parts.append(f"constexpr int {up}_FRAMES = {len(grids)};\n")
        parts.append(f"constexpr int {up}_COLOURS = {len(pal) + 1};\n\n")

        parts.append(f"static const uint8_t k{fam.capitalize()}Pal[{len(pal) + 1}][3] = {{\n")
        parts.append("  {   0,   0,   0 },   // 0 = transparent, never read\n")
        for ch, (r, g, b) in pal:
            parts.append(f"  {{ {r:3d}, {g:3d}, {b:3d} }},   // '{ch}'\n")
        parts.append("};\n\n")

        # A family whose tier is a whole-palette swap carries one palette per
        # tier as well. render.cpp indexes this by game::ToolTier, and the
        # order here is that enum's order.
        if fam in TIER_PALETTES:
            tp = TIER_PALETTES[fam]
            if any(len(t) != len(pal) for t in tp):
                sys.exit(f"{fam}: a tier palette is not {len(pal)} entries long")
            parts.append(f"static const uint8_t k{fam.capitalize()}TierPal"
                         f"[{len(tp)}][{len(pal) + 1}][3] = {{\n")
            for name, t in zip(["wood", "stone", "iron", "diamond"], tp):
                parts.append(f"  {{  // {name}\n")
                parts.append("    {   0,   0,   0 },\n")
                for (r, g, b) in t:
                    parts.append(f"    {{ {r:3d}, {g:3d}, {b:3d} }},\n")
                parts.append("  },\n")
            parts.append("};\n\n")

        parts.append(
            f"static const uint8_t k{fam.capitalize()}[{len(grids)}][{h}][{w}] = {{\n")
        for gi, g in enumerate(grids):
            parts.append("  {\n")
            for row in g:
                parts.append("    { " + ",".join(str(v) for v in row) + " },\n")
            parts.append("  },\n")
        parts.append("};\n\n")

    # A table so render.cpp can index by game::MobKind without a switch.
    parts.append(
        "// Indexed by game::MobKind. The order here is the enum's order, and the\n"
        "// static_assert in render.cpp is what keeps it that way.\n"
        "struct MobArt {\n"
        "  const uint8_t* pix;      // FRAMES * H * W\n"
        "  const uint8_t (*pal)[3];\n"
        "  uint8_t w, h, frames, colours;\n"
        "  uint8_t walk;            // frames [0, walk) are the walk cycle;\n"
        "                           // [walk, frames) are attack poses\n"
        "  float   worldH;          // how tall it stands, in blocks\n"
        "};\n\n"
        "static const MobArt kMobArt[3] = {\n"
    )
    heights = {"zombie": 1.85, "creeper": 1.60, "skeleton": 1.90}
    for fam in MOB_ORDER:
        # render.cpp takes a modulo by this to pick a stride frame, so zero
        # would divide by zero on the device. Checked here rather than guarded
        # there: it is a fact about the art, and the art is written here.
        n = len(SPRITES[fam])
        if not 1 <= WALK_FRAMES[fam] <= n:
            sys.exit(f"{fam}: WALK_FRAMES is {WALK_FRAMES[fam]}, "
                     f"must be between 1 and the {n} frames it has")
        up, cap = fam.upper(), fam.capitalize()
        parts.append(
            f"  {{ &k{cap}[0][0][0], k{cap}Pal, {up}_W, {up}_H, "
            f"{up}_FRAMES, {up}_COLOURS, {WALK_FRAMES[fam]}, "
            f"{heights[fam]:.2f}f }},\n")
    parts.append("};\n\n}  // namespace sprites\n")

    path.write_text("".join(parts))
    print(f"wrote {path}")

def show():
    for fam, frames in SPRITES.items():
        pal = PALETTES[fam]
        legend = {ch: i + 1 for i, (ch, _) in enumerate(pal)}
        rev = {i + 1: ch for i, (ch, _) in enumerate(pal)}
        for i, art in enumerate(frames):
            g, w, h = parse(art, legend, fam, i)
            print(f"\n{fam} frame {i}  {w}x{h}")
            for row in g:
                print("  " + "".join(rev.get(v, ".") for v in row))

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--show", action="store_true")
    ap.add_argument("--out", type=Path, default=Path("src/sprites.h"))
    args = ap.parse_args()
    if args.show:
        show()
    else:
        emit(args.out)

if __name__ == "__main__":
    main()
