#!/usr/bin/env python3
"""Generate src/sprites.h from the pixel art below.

The renderer owns a raw pre-swapped RGB565 framebuffer and cannot use M5GFX's
drawing calls on it, so sprites are blitted by hand from an indexed bitmap.
Keeping the art as ASCII here — rather than as hand-written hex, or as stacks of
coloured rectangles in render.cpp — is the whole point of this script: the art
is reviewable in a diff, and the packing is done once by a machine that does not
make bit-order mistakes. tools/make-font.py does the same for the HUD font.

    ./tools/make-sprites.py            # rewrite src/sprites.h
    ./tools/make-sprites.py --show     # unpack the result and print it back

Encoding: one byte per pixel, palette index, row-major. Index 0 is transparent.
Each sprite family carries its own palette of up to 15 colours; the renderer
pre-shades that palette once per drawn instance for distance and light, so the
inner loop is a plain index-and-store.

House style for the art itself:
  '.'  transparent
  '#'  outline — always the darkest colour, always a full ring around the
       silhouette. This is what makes a sprite read against terrain of a
       similar colour, and it is drawn into the art rather than inflated at
       runtime so it costs nothing and never doubles on interior edges.
  others  shades, dark to light, so every surface has at least three.
"""

import argparse
import sys
from pathlib import Path

# Palettes. Index 0 is transparent and never appears in the art.
PALETTES = {
    "zombie": [
        ("#", (16, 18, 22)),     # outline
        ("x", (24, 30, 26)),     # eye socket
        ("a", (58, 96, 60)),     # skin, shadow
        ("b", (92, 148, 88)),    # skin, mid
        ("c", (128, 186, 118)),  # skin, lit
        ("d", (28, 60, 82)),     # trousers, shadow
        ("e", (44, 88, 116)),    # trousers, lit
        ("f", (26, 88, 76)),     # shirt, shadow
        ("g", (42, 128, 104)),   # shirt, mid
        ("h", (66, 162, 132)),   # shirt, lit
    ],
    "creeper": [
        ("#", (12, 20, 12)),
        ("x", (16, 34, 16)),     # the face
        ("a", (38, 96, 40)),     # shadow
        ("b", (66, 150, 62)),    # mid
        ("c", (98, 190, 88)),    # lit
        ("d", (128, 214, 108)),  # highlight
    ],
    "skeleton": [
        ("#", (18, 18, 22)),
        ("x", (22, 22, 28)),     # sockets
        ("a", (132, 132, 126)),  # bone, shadow
        ("b", (186, 186, 178)),  # bone, mid
        ("c", (228, 228, 220)),  # bone, lit
        ("d", (74, 52, 32)),     # bow, shadow
        ("e", (116, 84, 50)),    # bow, lit
    ],
    # The tool. Metal gets four steps and wood three, which is what makes it
    # read as two materials rather than as one shape in two colours.
    "pick": [
        ("#", (14, 14, 16)),
        ("a", (74, 78, 86)),     # metal, shadow
        ("b", (126, 131, 140)),  # metal, mid
        ("c", (176, 181, 190)),  # metal, lit
        ("d", (222, 226, 232)),  # metal, highlight
        ("e", (74, 48, 28)),     # haft, shadow
        ("f", (118, 78, 42)),    # haft, mid
        ("g", (156, 110, 62)),   # haft, lit
    ],
    # The sword shares the pickaxe's ramp exactly, and it has to: render.cpp
    # swaps 'a'..'d' for the tier on whichever tool is in the hand, so the two
    # families have to agree on which four indices are the metal.
    "sword": [
        ("#", (14, 14, 16)),
        ("a", (74, 78, 86)),     # metal, shadow
        ("b", (126, 131, 140)),  # metal, mid
        ("c", (176, 181, 190)),  # metal, lit
        ("d", (222, 226, 232)),  # metal, highlight
        ("e", (74, 48, 28)),     # grip, shadow
        ("f", (118, 78, 42)),    # grip, mid
        ("g", (156, 110, 62)),   # grip, lit
    ],
}

# ---- mobs: 16 wide, 24 tall -------------------------------------------------
#
# Two walk frames each, and for anything that swings at you, attack poses after
# them. WALK_FRAMES below says where the walk cycle stops, because the renderer
# picks a walk frame with a modulo and would otherwise deal an attack pose out
# as part of the stride.
#
# The difference between frames is deliberately large — legs swapped and the
# whole body dropped a pixel — because at ten cells a subtle cycle is invisible
# and at two cells a subtle cycle looks like a rendering fault. The same goes
# double for the swing: at sixteen pixels wide there is no room for a subtle
# gesture, so the arms come in to the body to wind up and are thrown out past
# the silhouette to strike.

ZOMBIE = ["""
....########....
...#bbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#bcccccccb#...
..#bbcaaacbb#...
...##########...
....#ffffff#....
..###gggggg###..
.#abc#gghg#cba#.
.#abc#ghhg#cba#.
.#abc#ghhg#cba#.
.#abc#gggg#cba#.
.#abc#ffff#cba#.
.#bc##ffff##cb#.
..###dddddd###..
....#dd##dd#....
....#de##ed#....
....#de##ed#....
....#de##ed#....
....#dd##dd#....
....###.###.....
................
""", """
................
....########....
...#bbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#bcccccccb#...
..#bbcaaacbb#...
...##########...
....#ffffff#....
..###gggggg###..
.#abc#gghg#cba#.
.#abc#ghhg#cba#.
.#abc#ghhg#cba#.
.#abc#gggg#cba#.
.#bc##ffff##cb#.
..###dddddd###..
....#dd##dd#....
....#ed##de#....
....#ed##de#....
....#ed##de#....
....#dd##dd#....
....##.####.....
................
""", """
....########....
...#bbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#bcccccccb#...
..#bbcaaacbb#...
...##########...
....#ffffff#....
..###gggggg###..
..#ab#gghg#ba#..
..#bc#ghhg#cb#..
..#cc#ghhg#cc#..
..####gggg####..
.....#ffff#.....
....##ffff##....
..###dddddd###..
....#dd##dd#....
....#de##ed#....
....#de##ed#....
....#de##ed#....
....#dd##dd#....
....###.###.....
................
""", """
....########....
...#bbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#bcccccccb#...
..#bbcaaacbb#...
...##########...
....#ffffff#....
#####gggggg#####
#abcc#gghg#ccba#
#bccc#ghhg#cccb#
#cccc#ghhg#cccc#
######gggg######
.....#ffff#.....
....##ffff##....
..###dddddd###..
....#dd##dd#....
....#de##ed#....
....#de##ed#....
....#de##ed#....
....#dd##dd#....
....###.###.....
................
"""]

CREEPER = ["""
................
..###########...
..#bbbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#cccxxxccc#...
..#ccxxxxxcc#...
..#ccxxxxxcc#...
..#cccxxxccc#...
..#bcccccccb#...
..###########...
...#bbbbbbb#....
...#bcccccb#....
...#bcccccb#....
...#bcdddcb#....
...#bcccccb#....
...#bbbbbbb#....
...####.####....
...#aa#.#aa#....
...#ab#.#ba#....
...#ab#.#ba#....
...####.####....
................
""", """
................
..###########...
..#bbbbbbbbb#...
..#bcccccccb#...
..#cxxcccxxc#...
..#cxxcccxxc#...
..#cccxxxccc#...
..#ccxxxxxcc#...
..#ccxxxxxcc#...
..#cccxxxccc#...
..#bcccccccb#...
..###########...
...#bbbbbbb#....
...#bcccccb#....
...#bcdddcb#....
...#bcccccb#....
...#bcccccb#....
...#bbbbbbb#....
..#####.####....
..#aa#..#aa#....
..#ba#..#ab#....
..#ba#..#ab#....
..####..####....
................
"""]

SKELETON = ["""
....######......
...#bbbbbb#.....
..#bcccccb#.....
..#cxxcxxc#.....
..#cxxcxxc#.....
..#ccccccc#.....
..#cacacac#.....
...########.....
.....##.........
..##bbbbbb##....
.#d#cc##cc#b#...
.#e#cc##cc#b#...
.#e#cccccc#b#...
.#e#cc##cc#b#...
.#d#cccccc#b#...
..##bbbbbb##....
....#aaaa#......
....#a##a#......
....#c##c#......
....#c##c#......
....#b##b#......
....#a##a#......
....##.##.......
................
""", """
................
....######......
...#bbbbbb#.....
..#bcccccb#.....
..#cxxcxxc#.....
..#cxxcxxc#.....
..#ccccccc#.....
..#cacacac#.....
...########.....
.....##.........
..##bbbbbb##....
.#e#cc##cc#b#...
.#e#cc##cc#b#...
.#d#cccccc#b#...
.#e#cc##cc#b#...
.#e#cccccc#b#...
..##bbbbbb##....
....#aaaa#......
....#a##a#......
....#c##c#......
....#c##c#......
....#b##b#......
...##.##........
................
"""]

# ---- the pickaxe: 24 x 24 ---------------------------------------------------
#
# Head across the top with a curved bit at each end, haft running down to the
# right. Every surface is outlined and shaded dark-to-light, which is the whole
# difference between pixel art and a diagram: the old tool was drawn at runtime
# from rotated squares and read as a silhouette with no material in it.

# A pickaxe: one continuous head sweeping from a point at the upper right down
# to a point at the lower left, with the haft leaving its middle for the bottom
# corner. The open V between the head's lower arm and the haft is the whole
# silhouette; fill it in and what is left reads as a bent stick.
#
# Laid out from its geometry rather than typed in by hand — placing sloped runs
# a row at a time produced off-by-one edges every time — then pasted here so the
# art stays reviewable in a diff, which is the point of this file.
#
# Two things it went wrong on first, both visible from across the room:
#
#   * The head is in *front* of the handle it is fixed to. Drawing the haft last
#     punched a hole clean through the blade where the two cross, and the tool
#     looked snapped.
#   * The head has to taper to a point at both ends. At constant thickness it
#     stops being a pickaxe head and becomes a blade.
# The head is arched and its two ends are different: a point on one arm, a blunt
# chisel on the other. That asymmetry is the whole difference between a pickaxe
# and a hammer — a straight bar with matching tapers, which is what this was,
# reads as a mallet no matter how it is shaded. The collar under the eye is what
# stops the haft from looking like a stick passing behind the head.
#
# Redrawn into this palette rather than used as-is, because 'a'..'d' are not
# free colours: render.cpp swaps exactly those four for the tool tier, so the
# head has to be all four of them and the haft none. The import classified
# metal from wood on saturation, ranked each into its own ramp, and put the
# outline ring back the way the house style wants it.
PICK = ["""
.............####...............
............#cccc#..............
...........#ccdddc#.............
..........#abcdddc#.............
.........#aabccdc#..............
.......##aaaa####...............
......#aaaaa#...................
.....#aaaaa#....................
.....#bbbag#....................
....#bbbaeeg#...................
...#bbbbgeeeg#..................
..#bbbb##geeeg#.................
.#cbbb#..#geefg#................
#cdcc#....#geeeg#...............
#cddc#.....#geefg#..............
#dddd#......#gfeeg#.............
#dddc#.......#geefg#............
.#dd#.........#gfefg#...........
..##...........#gfefg#..........
................#gfefg#.........
.................#gfefg#........
..................#gfefg#.......
...................#gfefg#......
....................#gfeff#.....
.....................#gfeff#....
......................#ffegf#...
.......................#fgeff#..
........................#ffeff#.
.........................#fgeee#
..........................#fefg#
...........................#eg#.
............................##..
"""]

# ---- the sword: 32 x 32 -----------------------------------------------------
#
# Laid out from its geometry, like the pickaxe, and for the same reason: a
# blade on the diagonal cannot be typed in a row at a time. Placing it as
# points along the diagonal was tried first and produced a lattice with a hole
# between every pair of texels -- 45 degrees at unit steps does not join up.
# What works is treating it as a REGION: rasterise the band where |row - col|
# falls inside the blade's thickness, which is solid by construction.
#
# The tip is up and to the left because that is where the panel shows it. The
# anchor in render.cpp puts the art's centre below the bottom edge, so what is
# in frame is the top-left corner of the art and the grip runs off-screen into
# the hand -- exactly the arrangement the pickaxe's head and haft use.
SWORD = ["""
................................
..####..........................
..#bc###........................
..##bcd##.......................
...##bcd##......................
....##bcd##.....................
.....#abcd##....................
.....##abcd##...................
......##abcd##..................
.......##abcd##.................
........##abcd##................
.........##abcd##...............
..........##abcd##..............
...........##abcd##.............
............##abcd##............
.............##abcd##...........
..............##abcd##...###....
...............##abcd##.##a##...
................##abcd###aaa#...
.................##abcd#aaaa#...
..................##ab#baaa##...
...................###ccba##....
...................##abcc##.....
..................##aaab#e##....
..................#aaaa##fe##...
..................#aaa####fe##..
..................##a##..##fe##.
...................###....##fe##
...........................##fgf
............................#fgg
............................##fg
.............................###
"""]

SPRITES = {
    "zombie": ZOMBIE,
    "creeper": CREEPER,
    "skeleton": SKELETON,
    "pick": PICK,
    "sword": SWORD,
}

MOB_ORDER = ["zombie", "creeper", "skeleton"]

# How many of a family's frames are the walk cycle. Anything past this is an
# attack pose, reached from the mob's windup rather than from its stride.
WALK_FRAMES = {"zombie": 2, "creeper": 2, "skeleton": 2}

def parse(art, legend, name, idx):
    rows = [r for r in art.strip("\n").split("\n")]
    w = max(len(r) for r in rows)
    rows = [r.ljust(w, ".") for r in rows]
    out = []
    for y, row in enumerate(rows):
        line = []
        for x, ch in enumerate(row):
            if ch == ".":
                line.append(0)
            elif ch in legend:
                line.append(legend[ch])
            else:
                sys.exit(f"{name}[{idx}] row {y} col {x}: unknown glyph {ch!r}")
        out.append(line)
    return out, w, len(rows)

def emit(path):
    parts = []
    parts.append(
        "// =============================================================================\n"
        "//  sprites.h — GENERATED by tools/make-sprites.py. Do not edit by hand.\n"
        "//\n"
        "//  Indexed pixel art: one byte per pixel, palette index, row-major, 0 =\n"
        "//  transparent. Each family carries its own palette; render.cpp pre-shades it\n"
        "//  once per drawn instance for distance, light and hit flash, so the blit\n"
        "//  itself is an index and a store.\n"
        "//\n"
        "//  The outline is part of the art rather than an inflate-and-fill pass at\n"
        "//  runtime. That costs nothing, never doubles on interior edges, and is what\n"
        "//  lets a mob read against terrain of its own colour.\n"
        "// =============================================================================\n"
        "#pragma once\n\n#include <stdint.h>\n\nnamespace sprites {\n"
    )

    # Order is the emit order, and it is fixed here rather than taken from
    # SPRITES so that adding a family is a deliberate edit in two places.
    for fam in ["zombie", "creeper", "skeleton", "pick", "sword"]:
        pal = PALETTES[fam]
        legend = {ch: i + 1 for i, (ch, _) in enumerate(pal)}
        frames = SPRITES[fam]
        grids, w, h = [], None, None
        for i, art in enumerate(frames):
            g, gw, gh = parse(art, legend, fam, i)
            if w is None:
                w, h = gw, gh
            elif (gw, gh) != (w, h):
                sys.exit(f"{fam}: frame {i} is {gw}x{gh}, frame 0 is {w}x{h}")
            grids.append(g)

        up = fam.upper()
        parts.append(f"// ---- {fam} ----\n")
        parts.append(f"constexpr int {up}_W = {w};\n")
        parts.append(f"constexpr int {up}_H = {h};\n")
        parts.append(f"constexpr int {up}_FRAMES = {len(grids)};\n")
        parts.append(f"constexpr int {up}_COLOURS = {len(pal) + 1};\n\n")

        parts.append(f"static const uint8_t k{fam.capitalize()}Pal[{len(pal) + 1}][3] = {{\n")
        parts.append("  {   0,   0,   0 },   // 0 = transparent, never read\n")
        for ch, (r, g, b) in pal:
            parts.append(f"  {{ {r:3d}, {g:3d}, {b:3d} }},   // '{ch}'\n")
        parts.append("};\n\n")

        parts.append(
            f"static const uint8_t k{fam.capitalize()}[{len(grids)}][{h}][{w}] = {{\n")
        for gi, g in enumerate(grids):
            parts.append("  {\n")
            for row in g:
                parts.append("    { " + ",".join(str(v) for v in row) + " },\n")
            parts.append("  },\n")
        parts.append("};\n\n")

    # A table so render.cpp can index by game::MobKind without a switch.
    parts.append(
        "// Indexed by game::MobKind. The order here is the enum's order, and the\n"
        "// static_assert in render.cpp is what keeps it that way.\n"
        "struct MobArt {\n"
        "  const uint8_t* pix;      // FRAMES * H * W\n"
        "  const uint8_t (*pal)[3];\n"
        "  uint8_t w, h, frames, colours;\n"
        "  uint8_t walk;            // frames [0, walk) are the walk cycle;\n"
        "                           // [walk, frames) are attack poses\n"
        "  float   worldH;          // how tall it stands, in blocks\n"
        "};\n\n"
        "static const MobArt kMobArt[3] = {\n"
    )
    heights = {"zombie": 1.85, "creeper": 1.60, "skeleton": 1.90}
    for fam in MOB_ORDER:
        # render.cpp takes a modulo by this to pick a stride frame, so zero
        # would divide by zero on the device. Checked here rather than guarded
        # there: it is a fact about the art, and the art is written here.
        n = len(SPRITES[fam])
        if not 1 <= WALK_FRAMES[fam] <= n:
            sys.exit(f"{fam}: WALK_FRAMES is {WALK_FRAMES[fam]}, "
                     f"must be between 1 and the {n} frames it has")
        up, cap = fam.upper(), fam.capitalize()
        parts.append(
            f"  {{ &k{cap}[0][0][0], k{cap}Pal, {up}_W, {up}_H, "
            f"{up}_FRAMES, {up}_COLOURS, {WALK_FRAMES[fam]}, "
            f"{heights[fam]:.2f}f }},\n")
    parts.append("};\n\n}  // namespace sprites\n")

    path.write_text("".join(parts))
    print(f"wrote {path}")

def show():
    for fam, frames in SPRITES.items():
        pal = PALETTES[fam]
        legend = {ch: i + 1 for i, (ch, _) in enumerate(pal)}
        rev = {i + 1: ch for i, (ch, _) in enumerate(pal)}
        for i, art in enumerate(frames):
            g, w, h = parse(art, legend, fam, i)
            print(f"\n{fam} frame {i}  {w}x{h}")
            for row in g:
                print("  " + "".join(rev.get(v, ".") for v in row))

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--show", action="store_true")
    ap.add_argument("--out", type=Path, default=Path("src/sprites.h"))
    args = ap.parse_args()
    if args.show:
        show()
    else:
        emit(args.out)

if __name__ == "__main__":
    main()
